### ISSUE TITLE
Invalid file size if multiple data streams are available

### ISSUE THREAD

**Issue by icewind1991** [icewind1991/SMB#36]
> When an Alternate Data Stream Information was stored incorrect by an Apple Machine on the windows server, the parser failed sometimes detecting a valid file size.
> 
> In function parseStat($output), $output will get the following values:
> 
> array(8) {
>   [0]=>
>   string(21) "altname: GEO-AU~2.PDF"
>   [1]=>
>   string(48) "create_time:    Sat Oct 24 12:21:07 PM 2015 CEST"
>   [2]=>
>   string(48) "access_time:    Sat Oct 24 12:21:07 PM 2015 CEST"
>   [3]=>
>   string(47) "write_time:     Sat Feb 21 02:16:03 PM 2015 CET"
>   [4]=>
>   string(48) "change_time:    Wed Oct 21 07:38:53 PM 2015 CEST"
>   [5]=>
>   string(18) "attributes: A (20)"
>   [6]=>
>   string(33) "stream: [::$DATA], 59948812 bytes"
>   [7]=>
>   string(38) "stream: [:AFP_AfpInfo:$DATA], 60 bytes" <-- this line is the evil! 
> }
> 
> $size, which is responsible for the http meta tag content-length will get the AFP information out of line 7, NOT the size of line 6.
> 
> I resolved this issue using an additional check:
> ... else if (($name === 'stream') && (strpos($line, 'AFP_AfpInfo') == false)) { ...

Reported by Jens Haag over mail

**Comment by Diak** [comment]
I use Owncloud 8.2.2 and External_files module so i can add SMB external storage folder.
When I try to download some big files, the size displayed on Owncloud interface is correct but when the download size (http meta tag content-length) is wrong so the download is not completed.

I tried the solution above but by editing /var/www/owncloud//apps/files_external/3rdparty/icewind/smb/src/Parser.php file but the problem is not solved.

Is there any other solution ? It's blocking :-/
