### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by BBrunekreeft** [icewind1991/SMB#58]
The latest release 2.0.2 doesn't have the fix "make authfile handling compatible with smbclient 4.6.x" (commit 6723c97de1b21a4f414b895a5bb0c4cb5d120440)
Is it possible to make a new release with this fix included?

**Comment by hashbou** [comment]
There are some more parts which are missing in the releases:
https://github.com/icewind1991/SMB/blob/8394551bf29a37b884edb33dae8acde369177f32/src/Exception/Exception.php#L17

The fix was introduced 3 months ago with the following commit: https://github.com/icewind1991/SMB/commit/79b69c635b23abf7d90fabd1dcd7d6046f519955

I would be thankful if this fix finds place in the upcoming releases. 

Thank you in Advance.

**Comment by icewind1991** [comment]
Fixed with 2.0.3
